from base_enum import BaseEnum


class StatTypes(str, BaseEnum):
    # extend as needed
    STRENGTH = "strength"
    DEXTERITY = "dexterity"
    CONSTITUTION = "constitution"
    INTELLIGENCE = "intelligence"
    CUNNING = "cunning"
    WILLPOWER = "willpower"
    HP = "hp"
    HP_REGEN = "hp regen"
    ENERGY = "energy"
    ENERGY_REGEN = "energy regen"
    MANA = "mana"
    MANA_REGEN = "mana regen"
    CARRYING_CAPACITY = "carrying capacity"
    ENCUMBRANCE = "encumbrance"
    DAMAGE_RESISTS = "damage resists"
    DAMAGE_AMPS = "damage amps"
    DAMAGE_MASTERIES = "damage masteries"
    FLAT_WEAPON_ATTACK = "flat weapon attack"
    FLAT_WEAPON_DAMAGE = "flat weapon damage"
    FLAT_ARMOR_DEFENSE = "flat armor defense"
    GLOBAL_SPEED = "global speed"
    ATTACK_SPEED = "attack speed"
    MOVEMENT_SPEED = "movement speed"
    CASTING_SPEED = "casting speed"
    CRITICAL_CHANCE = "critical chance"
    CRITICAL_MULTIPLIER = "critical_multiplier"
